name: Store Job Logs as Artifact

on:
  workflow_dispatch:
    inputs:
        PRODUCT_NAME:
            type: string
            description:  'path to the deploy guide file underneath doc/deploy_guides folder(e.g 2023.3.0.md)'
        DEPLOYMENT_STATUS:
          type: string
          description:  'Deployment status (passed)'
        deployed_by:
          type: string
          description:  'who deployed (e.g. ctemouatchonke)'
        environment:
          type: string
          description:  'environment (e.g. validation)'
        commit:
          type: string
          description:  'commit hash (e.g. 1234567890)'
        date:
          type: string
          description:  'date (e.g. 12:30pm)'
        PRODUCT_URL: 
          type: string
          description: 'product url (eg. "N/A(AWS LAMBDA does not have an URL because is a serverless service)"
  


jobs:
  store_logs:
    runs-on: ubuntu-latest

    container:
        image: pandoc/latex:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run your build/test/deployment steps here
      # For demonstration purposes, we'll create a dummy log file
      - name: Generate logs
        run: cp -rf src/text.md mylog.md

      - name: Convert Logs to PDF
        run: |
          # Assuming your logs are in markdown format
          pandoc -o Cpp-configs_logs.pdf mylog.md -V geometry:margin=0.15in

      # Store the log file as an artifact
      - name: Store PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted_logs
          path: Cpp-configs_logs.pdf
