name: practice workflow
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - name: npm run lint
         run: eslint --ext .jsx --fix sr
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
     - name: test the code
       run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
        - name: build the code
          run: npm run build
         - name: Deployment
          echo "Deploying..." 
