name: practice workflow
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - name: run lint
         run: eslint --ext .jsx --fix sr
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
     - name: test the code
       run: vitest run
  build:
    runs-on: ubuntu-latest
    steps:
        - name: build the code
          run: vite build
