name: Output information
on: workflow_dispatch
jobs:
  Infos:
    runs-on: ubuntu-latest
    steps:
    - name: convert file to pdf 
      run: pandoc -s -o moute.pdf text.md -V geometry:margin=0.15in
    - name: Uplaod artifact
      uses: actions/upload-artifact@v4
      with:
        name: tacs-artifact
        path: moute.pdf
