name: Output information
on: workflow_dispatch
jobs:
  Infos:
    runs-on: ubuntu-latest
    container:
        image: pandoc/latex:latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v3

    - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  
    - name: convert file to pdf 
      run: pandoc -s -o moute.pdf src/2023.3.3.md -V geometry:margin=0.15in
    - name: Uplaod artifact
      uses: actions/upload-artifact@v4
      with:
        name: tacs-artifact
        path: moute.pdf
