name: practice workflow
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - name: run lint
         run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
     - name: test the code
       run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deploying..."
      - name: actions/upload-artifact@v4
        with:
          name:tacs-artifact
          path: |
             package.json
             index.html
