name: Upload Artifact to S3

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload artifact to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'your-region' # replace 'your-region' with your S3 bucket region
        run: |
          aws s3 cp "./13-awscli_1.22.34-1_all.deb" "s3://artifact-tests3/moute"
